name: Run PHPUnit tests

on:
  push:
    branches:
      - main
      - 'feature/*'
  pull_request:
    branches:
      - main

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, dom
          ini-values: post_max_size=256M, upload_max_filesize=256M, memory_limit=512M
          coverage: xdebug

      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist
        env:
          COMPOSER_CACHE_DIR: /tmp/composer_cache # Usar cache para evitar problemas de conexão

      - name: Run PHPUnit
        run: ./vendor/bin/phpunit --coverage-text --colors=never

      - name: Upload test results if failed
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: phpunit-results
          path: ./tests/_output/
